Create My Product 
Create a modern AI-powered web application called UbuntuAI: South African Workplace Compliance & Productivity Assistant. 
Tagline 
"Helping South African businesses work smarter, communicate better, and stay compliant." 
Project Overview 
UbuntuAI is designed to help South African Small and Medium Enterprises (SMEs) automate repetitive workplace tasks, improve productivity, and support workplace compliance awareness. 
Many businesses struggle with drafting professional emails, managing employee tasks, tracking meeting outcomes, researching workplace policies, and maintaining productivity with limited resources. 
UbuntuAI provides a centralized AI assistant that simplifies these activities through intelligent automation while promoting responsible AI usage. 
 
Target Users 
Small Business Owners 
Office Administrators 
HR Officers 
Team Leaders 
Operations Managers 
Project Managers 
Freelancers 
Entrepreneurs 
 
Application Layout 
Create a professional dashboard with a modern blue-and-white corporate design. 
Dashboard Widgets 
Quick Actions Panel 
Recent Activity 
AI Workplace Assistant 
Task Overview 
Meeting Summary History 
Compliance Research Hub 
Sidebar Navigation 
Dashboard 
Smart Email Generator 
Meeting Minutes & Action Tracker 
Employee Task Planner 
Workplace Research Assistant 
UbuntuAI Chatbot 
Prompt Library 
Settings 
Responsive Design 
The application must be fully responsive and optimized for: 
Desktop 
Laptop 
Tablet 
Mobile 
 
Core Features 
1. Smart Workplace Email Generator 
Allow users to generate: 
Employee warning letters 
Leave approval emails 
Performance feedback 
Meeting invitations 
Client communication 
Internal announcements 
Inputs 
Email purpose 
Recipient type 
Tone (Formal, Informal, Persuasive) 
Outputs 
Subject line 
Professional email body 
Closing statement 
 
2. Meeting Minutes & Action Tracker 
Allow users to paste meeting notes or transcripts. 
AI should generate: 
Meeting summary 
Key discussion points 
Decisions made 
Action items 
Responsible persons 
Due dates 
Display results in a structured table. 
 
3. Employee Task Planner & Scheduler 
Allow managers to enter: 
Tasks 
Deadlines 
Priority levels 
AI should create: 
Daily schedule 
Weekly planner 
Time-block recommendations 
Productivity suggestions 
 
4. South African Workplace Research Assistant 
Allow users to ask workplace-related questions such as: 
Leave entitlement 
Notice periods 
Overtime guidelines 
Disciplinary procedures 
Workplace best practices 
AI should provide: 
Simplified explanations 
Key insights 
Recommendations 
Executive summaries 
 
5. UbuntuAI Workplace Chatbot 
Create a conversational chatbot that can: 
Draft workplace documents 
Summarize meetings 
Generate schedules 
Answer workplace questions 
Assist with productivity tasks 
The chatbot should act as an expert South African Workplace Productivity and Compliance Assistant. 
 
Prompt Engineering Framework 
Use the following structure for all AI interactions: 
Role: 
You are an expert South African Workplace Productivity and Compliance Assistant. 
Task: 
Complete the requested workplace task. 
Context: 
Use South African workplace best practices where applicable. 
Requirements: 
Provide accurate, professional, actionable outputs. 
Output Format: 
Structured, easy to understand, and business-ready. 
 
Responsible AI Requirements 
Display a visible Responsible AI notice on every page. 
AI Disclaimer 
The information generated by UbuntuAI is intended to assist users with workplace productivity and compliance-related tasks. 
Users should: 
Review all AI-generated outputs before use 
Verify workplace and legal information independently 
Consult HR or legal professionals where necessary 
Avoid uploading confidential business information 
UbuntuAI does not replace professional legal, HR, financial, or compliance advice. 
 
User Experience Requirements 
Modern corporate UI 
Professional blue and white theme 
Card-based layouts 
Clear navigation 
Fast loading indicators 
Copy-to-clipboard functionality 
Download results as PDF 
Session history 
Clean typography 
Mobile-friendly design 
 
Evaluation Alignment 
The application must clearly demonstrate: 
Problem Relevance 
Solves real workplace productivity and compliance challenges faced by South African SMEs. 
Prompt Engineering 
Uses structured prompts with Role, Task, Context, Requirements, and Output Format. 
Functionality 
Includes Email Generator, Meeting Summarizer, Task Planner, Research Assistant, and Chatbot. 
Innovation 
Combines workplace productivity tools with compliance awareness tailored for South African businesses. 
Responsible AI 
Includes human oversight, privacy protection, bias awareness, and AI disclaimers. 
Presentation Quality 
Professional dashboard, responsive design, modern UI/UX, organized navigation, and business-ready outputs. 
 
Expected Outcome  
Build a fully functional AI Workplace Compliance and Productivity Assistant that improves workplace efficiency, reduces administrative workload, supports informed decision-making, and demonstrates practical AI implementation for South African businesses. 
 
Design Style: 
 
Use a modern corporate design inspired by Ubuntu and South African innovation. 
 
Apply subtle South African flag colours: 
- Green for success and productivity 
- Gold for growth and opportunity 
- Blue for trust and professionalism 
 
Use these colours in buttons, icons, navigation menus, and dashboard highlights. 
 
The interface should feel modern, clean, professional, mobile-friendly, and proudly South African without being overly colourful or distracting. 
 
Brand Message: 
"UbuntuAI – Working together through intelligent workplace solutions." 
