/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated.research'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated.prompts'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated.meetings'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated.email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated.chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/prompts'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/api/chat'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/prompts'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/api/chat'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/meetings'
    | '/_authenticated/prompts'
    | '/_authenticated/research'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
